# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxEr9p_Vn-nXHhYUinzGLZLxu-tV7pEd
"""

# Tic-Tac-Toe: Human always wins
# Computer is designed to lose

# Create empty board
board = [' ' for _ in range(9)]


# Display the board
def print_board():
    print()
    print(f" {board[0]} | {board[1]} | {board[2]} ")
    print("---+---+---")
    print(f" {board[3]} | {board[4]} | {board[5]} ")
    print("---+---+---")
    print(f" {board[6]} | {board[7]} | {board[8]} ")
    print()


# Check winner
def check_winner(player):
    winning_positions = [
        (0, 1, 2),
        (3, 4, 5),
        (6, 7, 8),
        (0, 3, 6),
        (1, 4, 7),
        (2, 5, 8),
        (0, 4, 8),
        (2, 4, 6)
    ]

    for a, b, c in winning_positions:
        if board[a] == board[b] == board[c] == player:
            return True

    return False


# Check draw
def is_draw():
    return ' ' not in board


# Computer move
# Computer intentionally chooses a bad move
def computer_move():

    # Fixed order of positions.
    # Computer will not play intelligently.
    bad_moves = [1, 3, 5, 7, 8, 2, 4, 6, 0]

    for move in bad_moves:
        if board[move] == ' ':
            board[move] = 'O'
            return


# Human move
def human_move():

    while True:
        try:
            move = int(input("Enter your position (1-9): "))

            if move < 1 or move > 9:
                print("Please enter a number between 1 and 9.")

            elif board[move - 1] != ' ':
                print("That position is already occupied.")

            else:
                board[move - 1] = 'X'
                break

        except ValueError:
            print("Please enter a valid number.")


# Main game
def play_game():

    print("===== TIC-TAC-TOE =====")
    print("You = X")
    print("Computer = O")
    print()

    print("Positions:")
    print(" 1 | 2 | 3 ")
    print("---+---+---")
    print(" 4 | 5 | 6 ")
    print("---+---+---")
    print(" 7 | 8 | 9 ")

    while True:

        # Human turn
        print("\nYour turn!")
        human_move()

        print_board()

        # Check human winner
        if check_winner('X'):
            print("🎉 You win!")
            break

        # Check draw
        if is_draw():
            print("It's a draw!")
            break


        # Computer turn
        print("Computer is thinking...")

        computer_move()

        print_board()

        # Check computer winner
        if check_winner('O'):
            print("Computer wins!")
            break

        # Check draw
        if is_draw():
            print("It's a draw!")
            break


# Start game
play_game()
