# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PO5Qomc1_FA4zJ_2WFLeGRnuoHBOsEci
"""

# Vacuum Cleaner Agent
# 2 Rooms: A and B

# Initial state
room_A = "DIRTY"
room_B = "DIRTY"

# Vacuum starts in Room A
location = "A"

print("Initial State")
print("Vacuum:", location)
print("Room A:", room_A)
print("Room B:", room_B)

# Agent works until both rooms are clean
while room_A == "DIRTY" or room_B == "DIRTY":

    if location == "A":

        # If Room A is dirty, clean it
        if room_A == "DIRTY":
            print("\nRoom A is DIRTY")
            print("Action: SUCK")
            room_A = "CLEAN"

        # If Room A is clean, move to Room B
        else:
            print("\nRoom A is CLEAN")
            print("Action: MOVE RIGHT")
            location = "B"

    else:  # Vacuum is in Room B

        # If Room B is dirty, clean it
        if room_B == "DIRTY":
            print("\nRoom B is DIRTY")
            print("Action: SUCK")
            room_B = "CLEAN"

        # If Room B is clean, move to Room A
        else:
            print("\nRoom B is CLEAN")
            print("Action: MOVE LEFT")
            location = "A"


# Goal state
print("\n==========================")
print("GOAL STATE REACHED!")
print("Room A:", room_A)
print("Room B:", room_B)
print("Vacuum Location:", location)
print("Both rooms are CLEAN.")
print("==========================")
